"""remove maximum amount

Revision ID: 018d0bfbbc11
Revises: 95fc0cbe1b6a
Create Date: 2026-07-14 12:01:18.138375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018d0bfbbc11'
down_revision: Union[str, Sequence[str], None] = '95fc0cbe1b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_plans', 'maximum_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_plans', sa.Column('maximum_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
