"""make registration fields nullable

Revision ID: 1885ac4c2398
Revises: 561deeab293d
Create Date: 2026-08-17 13:32:03.249772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1885ac4c2398'
down_revision: Union[str, Sequence[str], None] = '561deeab293d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'pan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'nominee_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'nominee_aadhar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'nominee_mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nominee_mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'nominee_aadhar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'nominee_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'pan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
