"""add payout method and information to payout history

Revision ID: 1c73bc7d7f2b
Revises: 52e3d94f3db7
Create Date: 2026-08-15 20:24:51.403153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c73bc7d7f2b'
down_revision: Union[str, Sequence[str], None] = '52e3d94f3db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
