"""update investment plan model

Revision ID: 2079e0a6f521
Revises: 32025a5d8b4e
Create Date: 2026-08-12 22:39:56.998364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2079e0a6f521'
down_revision: Union[str, Sequence[str], None] = '32025a5d8b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_plans', sa.Column('daily_commission_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_plans', 'daily_commission_limit')
    # ### end Alembic commands ###
