"""add investment plan to admin fee

Revision ID: 32025a5d8b4e
Revises: 90535af8c673
Create Date: 2026-08-12 14:45:21.066901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32025a5d8b4e'
down_revision: Union[str, Sequence[str], None] = '90535af8c673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_fee_settings', sa.Column('investment_plan_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'admin_fee_settings', 'investment_plans', ['investment_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_fee_settings', type_='foreignkey')
    op.drop_column('admin_fee_settings', 'investment_plan_id')
    # ### end Alembic commands ###
