"""add bank proof to users

Revision ID: 334a2242a299
Revises: f3efb9ab80b9
Create Date: 2026-08-07 16:44:00.738585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334a2242a299'
down_revision: Union[str, Sequence[str], None] = 'f3efb9ab80b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_proof', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_proof')
    # ### end Alembic commands ###
