"""add criteria to rank settings

Revision ID: 3cbb020780bf
Revises: 86d3bf4df314
Create Date: 2026-08-16 17:47:19.040222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbb020780bf'
down_revision: Union[str, Sequence[str], None] = '86d3bf4df314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_settings', sa.Column('criteria', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank_settings', 'criteria')
    # ### end Alembic commands ###
