"""update user table

Revision ID: 4da2eb397315
Revises: 33d1b144f94e
Create Date: 2026-07-21 16:27:30.339483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da2eb397315'
down_revision: Union[str, Sequence[str], None] = '33d1b144f94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('placement_parent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'placement_parent')
    # ### end Alembic commands ###
