"""add bank rejection reason

Revision ID: 5653ee51df99
Revises: e34cb2854b32
Create Date: 2026-08-21 17:06:46.847300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5653ee51df99'
down_revision: Union[str, Sequence[str], None] = 'e34cb2854b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_rejection_reason')
    # ### end Alembic commands ###
