"""commission payment fields

Revision ID: 60338eb2f65d
Revises: d395d35a036d
Create Date: 2026-07-20 15:16:28.136515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60338eb2f65d'
down_revision: Union[str, Sequence[str], None] = 'd395d35a036d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_commissions', sa.Column('payment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_commissions', 'payment_date')
    # ### end Alembic commands ###
