"""create sponsor commission tables coulumn update

Revision ID: 6577dbfcdbae
Revises: bbf942e74cfd
Create Date: 2026-07-17 12:18:22.817425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6577dbfcdbae'
down_revision: Union[str, Sequence[str], None] = 'bbf942e74cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('referral_commissions_to_user_id_fkey'), 'referral_commissions', type_='foreignkey')
    op.drop_column('referral_commissions', 'to_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_commissions', sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('referral_commissions_to_user_id_fkey'), 'referral_commissions', 'users', ['to_user_id'], ['id'])
    # ### end Alembic commands ###
