"""add admin notifications

Revision ID: 7871a85517e2
Revises: 8998fe4ba54f
Create Date: 2026-08-27 15:17:09.110146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7871a85517e2'
down_revision: Union[str, Sequence[str], None] = '8998fe4ba54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_return_date_settings_id'), 'return_date_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_date_settings_id'), table_name='return_date_settings')
    # ### end Alembic commands ###
