"""add rank tables

Revision ID: 810dd0015e9f
Revises: c0d9721b43ec
Create Date: 2026-08-01 11:37:05.242749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '810dd0015e9f'
down_revision: Union[str, Sequence[str], None] = 'c0d9721b43ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'investments', ['bank_transaction_id'])
    op.add_column('rank_conditions', sa.Column('order_no', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('current_rank_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'rank_settings', ['current_rank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'current_rank_id')
    op.drop_column('rank_conditions', 'order_no')
    op.drop_constraint(None, 'investments', type_='unique')
    # ### end Alembic commands ###
