"""create admin fee settings table

Revision ID: 90535af8c673
Revises: 334a2242a299
Create Date: 2026-08-12 14:23:57.680289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90535af8c673'
down_revision: Union[str, Sequence[str], None] = '334a2242a299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_plans', 'daily_commission_limit')
    op.drop_column('investment_plans', 'admin_fee_percentage')
    op.drop_column('investment_plans', 'commission_percentage')
    op.add_column('referral_commission_settings', sa.Column('daily_commission_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_commission_settings', 'daily_commission_limit')
    op.add_column('investment_plans', sa.Column('commission_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('investment_plans', sa.Column('admin_fee_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('investment_plans', sa.Column('daily_commission_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
