"""create sponsor commission tables coulumn update

Revision ID: 93349af750db
Revises: 6577dbfcdbae
Create Date: 2026-07-17 12:21:15.023040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93349af750db'
down_revision: Union[str, Sequence[str], None] = '6577dbfcdbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_commissions', sa.Column('investment_id', sa.Integer(), nullable=False))
    op.add_column('referral_commissions', sa.Column('investment_amount', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'referral_commissions', 'investments', ['investment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral_commissions', type_='foreignkey')
    op.drop_column('referral_commissions', 'investment_amount')
    op.drop_column('referral_commissions', 'investment_id')
    # ### end Alembic commands ###
