"""investment_plans

Revision ID: 95fc0cbe1b6a
Revises: 6cb1e5c4bef2
Create Date: 2026-07-14 11:33:16.873354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fc0cbe1b6a'
down_revision: Union[str, Sequence[str], None] = '6cb1e5c4bef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('return_percentage', sa.Float(), nullable=False),
    sa.Column('minimum_amount', sa.Float(), nullable=False),
    sa.Column('maximum_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name')
    )
    op.create_index(op.f('ix_investment_plans_id'), 'investment_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_plans_id'), table_name='investment_plans')
    op.drop_table('investment_plans')
    # ### end Alembic commands ###
