"""investment plan updated

Revision ID: a6a8f9c8beb8
Revises: 0c3be812a589
Create Date: 2026-07-20 13:07:11.290558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a8f9c8beb8'
down_revision: Union[str, Sequence[str], None] = '0c3be812a589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_plans', sa.Column('admin_fee_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_plans', 'admin_fee_percentage')
    # ### end Alembic commands ###
