"""create sponsor commission tables coulumn update

Revision ID: bbf942e74cfd
Revises: 55962bbefb41
Create Date: 2026-07-17 12:16:51.058231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf942e74cfd'
down_revision: Union[str, Sequence[str], None] = '55962bbefb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_commissions', sa.Column('investor_id', sa.Integer(), nullable=False))
    op.add_column('referral_commissions', sa.Column('enroller_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('referral_commissions_from_user_id_fkey'), 'referral_commissions', type_='foreignkey')
    op.drop_constraint(op.f('referral_commissions_investment_id_fkey'), 'referral_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'referral_commissions', 'users', ['investor_id'], ['id'])
    op.create_foreign_key(None, 'referral_commissions', 'users', ['enroller_id'], ['id'])
    op.drop_column('referral_commissions', 'investment_id')
    op.drop_column('referral_commissions', 'from_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_commissions', sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('referral_commissions', sa.Column('investment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referral_commissions', type_='foreignkey')
    op.drop_constraint(None, 'referral_commissions', type_='foreignkey')
    op.create_foreign_key(op.f('referral_commissions_investment_id_fkey'), 'referral_commissions', 'investments', ['investment_id'], ['id'])
    op.create_foreign_key(op.f('referral_commissions_from_user_id_fkey'), 'referral_commissions', 'users', ['from_user_id'], ['id'])
    op.drop_column('referral_commissions', 'enroller_id')
    op.drop_column('referral_commissions', 'investor_id')
    # ### end Alembic commands ###
