"""update user table

Revision ID: c0d9721b43ec
Revises: b050b48e9600
Create Date: 2026-07-29 21:23:56.887157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d9721b43ec'
down_revision: Union[str, Sequence[str], None] = 'b050b48e9600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'enroller_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'enroller_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
