"""add paid_at to level commission history

Revision ID: d20fdbb08030
Revises: dd5429552986
Create Date: 2026-09-10 13:12:43.177397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20fdbb08030'
down_revision: Union[str, Sequence[str], None] = 'dd5429552986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_commission_history', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level_commission_history', 'paid_at')
    # ### end Alembic commands ###
