"""referral commission  updated

Revision ID: d395d35a036d
Revises: a6a8f9c8beb8
Create Date: 2026-07-20 13:25:56.536446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd395d35a036d'
down_revision: Union[str, Sequence[str], None] = 'a6a8f9c8beb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_commissions', sa.Column('admin_fee_percentage', sa.Float(), nullable=False))
    op.add_column('referral_commissions', sa.Column('admin_fee_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_commissions', 'admin_fee_amount')
    op.drop_column('referral_commissions', 'admin_fee_percentage')
    # ### end Alembic commands ###
