"""initial schema

Revision ID: edf6eb5bf1a3
Revises: 
Create Date: 2026-07-14 15:46:08.423938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf6eb5bf1a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('return_percentage', sa.Float(), nullable=False),
    sa.Column('minimum_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name')
    )
    op.create_index(op.f('ix_investment_plans_id'), 'investment_plans', ['id'], unique=False)
    op.create_table('return_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_type')
    )
    op.create_index(op.f('ix_return_types_id'), 'return_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('enroller_id', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('aadhar_no', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('return_type_id', sa.Integer(), nullable=False),
    sa.Column('investment_plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('monthly_return_percentage', sa.Float(), nullable=False),
    sa.Column('monthly_return_amount', sa.Float(), nullable=False),
    sa.Column('bank_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('payment_proof', sa.String(length=255), nullable=True),
    sa.Column('enroller_id', sa.String(length=20), nullable=True),
    sa.Column('investment_status', sa.String(length=20), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('return_which', sa.Integer(), nullable=True),
    sa.Column('return_balance', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['investment_plan_id'], ['investment_plans.id'], ),
    sa.ForeignKeyConstraint(['return_type_id'], ['return_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_return_types_id'), table_name='return_types')
    op.drop_table('return_types')
    op.drop_index(op.f('ix_investment_plans_id'), table_name='investment_plans')
    op.drop_table('investment_plans')
    # ### end Alembic commands ###
